### ISSUE TITLE
sparsecat-linux-amd64 missing

### ISSUE THREAD

**Issue by wdoerr** [linka-cloud/d2vm#12]
Running go install ./cmd/d2vm produces:
cmd/d2vm/run/util.go:35:12: pattern sparsecat-linux-amd64: no matching files found

The related file in util.go contains:
//go:embed sparsecat-linux-amd64

A potential reason why that is not found is due to the .ignorefile which contains
/cmd/d2vm/run/sparsecat-linux-amd64

That causes git to not include that file/folder

Could you please add it to the repository, or did I miss something on the structure?

**Comment by Adphi** [comment]
You need to run `go generate ./...` before `go install`
