### ISSUE TITLE
JFYI  a similar approach by Rancher with elemental-toolkit

### ISSUE THREAD

**Issue by j-landru** [linka-cloud/d2vm#17]
Just for your information Suse/Rancher activly works on a similar idea in a gitops approach.
See elemental-toolkit

- https://github.com/rancher/elemental-toolkit
- https://rancher.github.io/elemental-toolkit/docs/

Could be an interesting source of inspiration for your project.

Regards.

**Comment by Adphi** [comment]
Thanks @j-landru. I'm not sure it is that similar. It seems to me to be way more complex and the dependency on cloud-init is a no go as it requires python to be installed.
