### ISSUE TITLE
Does this tool convert only OS docker images like ubuntu/centos etc or any docker image like nginx etc?

### ISSUE THREAD

**Issue by sanketIntel** [linka-cloud/d2vm#3]
I am trying to convert docker image of my application but my VM is unable to boot. can someone please specify if this tool will convert any docker image or only OS docker image?

**Comment by Adphi** [comment]
Hi @sanketIntel  !

Can you please share you Dockerfile ?

**Comment by sanketIntel** [comment]
I am converting a docker image not using docker file.

**Comment by Adphi** [comment]
If the docker image is based on supported os (ubuntu/debian/alpine/centos) it should be able to run. 
Can you share the image you are trying to convert ?

**Comment by sanketIntel** [comment]
https://hub.docker.com/r/openvisualcloud/xeon-ubuntu1804-service-owt/tags

the latest tag I am trying.

**Comment by Adphi** [comment]
Ok, there seems to be a problem with the vmlinux path:

```
SeaBIOS (version 1.13.0-1ubuntu1.1)
Machine UUID 19f07ce7-b65a-4e17-994d-cee9301db875


iPXE (http://ipxe.org) 00:03.0 CA00 PCI2.10 PnP PMM+3FF8C740+3FECC740 CA00



Booting from Hard Disk...

SYSLINUX 6.04 EDD 20191223 Copyright (C) 1994-2015 H. Peter Anvin et al
Now booting the kernel from SYSLINUX...
Loading /boot/vmlinuz... failed: No such file or directory
boot:
```

I did not test with Ubuntu 18.04.6 LTS, I will take a look.

**Comment by Adphi** [comment]
I got it... on ubuntu 18.04 the `vmlinuz` and `initrd.img` symlink are not created at the same location... they are created the debian way: at the file system root.

I tried with the ubuntu 20.04 based image version, it works:
```bash
d2vm convert openvisualcloud/xeon-ubuntu2004-service-owt -o service-owt.qcow2 -d
```

**Comment by sanketIntel** [comment]
Yes, It is booting now. Thank you.
