### ISSUE TITLE
What to copy to /usr/local/bin/?

### ISSUE THREAD

**Issue by geneoes** [linka-cloud/d2vm#8]
After installation with `make build-dev`, what folder is supposed to be copied to `usr/local/bin/`? The whole root of the project?

I am getting `Command 'd2vm' not found`

**Comment by Adphi** [comment]
The `make build-dev` command builds the container and the binary. The output binary is at the root of the repository. Then you have to move it somewhere in your `$PATH`.

I updated the README.md and the Makefile to add a `make install` command. It will install the *d2vm* binary in the `$GOPATH`.

Does it works for you ?

**Comment by Adphi** [comment]
I just added [homebrew](https://brew.sh/) support to installation :

```bash
brew install linka-cloud/tap/d2vm
```

**Comment by geneoes** [comment]
> I just added [homebrew](https://brew.sh/) support to installation :
> 
> ```shell
> brew install linka-cloud/tap/d2vm
> ```

That went great!
I just had to manually install **qemu-utils** and **extlinux**
