### ISSUE TITLE
Error on VirtualBox image

### ISSUE THREAD

**Issue by geneoes** [linka-cloud/d2vm#9]
When running :

```
d2vm build -p MyP4Ssw0rd -f ubuntu.Dockerfile -o ubuntu.vdi .
```

```
Building docker image from ubuntu.Dockerfile
Inspecting image d2vm-4dca598b-8f4d-4c6e-b6c2-c36d145dcb2a
No network manager specified, using distribution defaults: netplan
Docker image based on Ubuntu 22.04.1 LTS (Jammy Jellyfish)
Building kernel enabled image
Creating vm image
Creating raw image
Mounting raw image
Build failed
Unmounting raw image
Failed to unmount
Error: losetup --show -f /tmp/d2vm/834629c7-f718-4d96-bbea-c7890c7a1a09/disk0.d2vm.raw: stdout:  stderr: losetup: cannot find an unused loop device
 error: exit status 1
```
I am running this inside an Ubuntu VirtualBox with a Windows host

**Comment by Adphi** [comment]
The relevant error is:

```
losetup: cannot find an unused loop device
```

Can you list the loop devices inside your vm ?

```bash
sudo losetup -a
```

If there is none, can you ensure the kernel module is available ?

```bash
lsmod | grep loop
```

and enable it:

```bash
modprobe loop
```

**Comment by Adphi** [comment]
Ah... you have to use **sudo** to build the image...

**Comment by geneoes** [comment]
> Ah... you have to use **sudo** to build the image...

Ahh right!
I didn't because when using sudo: ```Command 'd2vm' not found```
I installed it through  `brew install linka-cloud/tap/d2vm`

**Comment by Adphi** [comment]
I always forget... since ubuntu 20.04 the user's $PATH is not preserved by `sudo`, so you need to run with the `-E` flag:

```bash
sudo -E d2vm ...
```

**Comment by geneoes** [comment]
hey yeah I tried but same message

`sudo: d2vm: command not found`

**Comment by Adphi** [comment]
what is the output of `which d2vm` ?

**Comment by geneoes** [comment]
> what is the output of `which d2vm` ?

`/home/linuxbrew/.linuxbrew/bin/d2vm
`

**Comment by Adphi** [comment]
can you show me your `$PATH` ?

```
echo $PATH
```

**Comment by geneoes** [comment]
`/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin`

**Comment by Adphi** [comment]
Can you try `sudo env "PATH=$PATH" d2vm ...` ?

**Comment by geneoes** [comment]
That worked and the build finished successfully, thank you!

**Comment by Adphi** [comment]
You're welcome !
